### ISSUE TITLE
Point cloud of Fig 2 (b)

### ISSUE THREAD

**Issue by YuZhang-GitHub** [XPengZhao/NeRF2#14]
Thank you for the great work! I am just wondering if the point cloud data of Fig 2 (b) is included in the dataset link, it seems I couldn't find it in this repo as well as in the datasets. Thanks!

**Comment by XPengZhao** [comment]
Thanks for your intertest. I have uploaded the PCD file to the dataset (located under `RFID/point cloud`).

**Comment by YuZhang-GitHub** [comment]
Thank you so much for the prompt responses. Much appreciated!

**Comment by dylandronnier** [comment]
Hi,

First, thank you for making the code and datasets associated with this excellent paper publicly available.

I would like to reopen this issue because it seems that the coordinate system used in the PCD files is different from the one used to define the TX and RX positions in `tx_pos.csv` and `gateway_info.yml`.

Could you please check whether this is the case?

It might be related to #15 and #8
